### ISSUE TITLE
gray tap highlight on some mobile browsers

### ISSUE THREAD

**Issue by chucklorenz** [cgkineo/adapt-hotgrid#32]
On some mobile webkit-based browsers, a tap highlight is standard. Typically it appears as a transparent gray overlay on the button. This is visible with Hot Grid items, especially those that use circular images because the button's actual dimensions are rectangular. Because Hot Grid responds to a tap (select) by opening a popup, I think the tap-highlight behaviour is unneeded and distracting.

I have been able to eliminate the bahaviour with 
```less
.hotgrid-component {
   button.base.hotgrid-item-image {       
        -webkit-tap-highlight-color: rgba(0,0,0,0);
    }
}
```
